DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER (
    ID varchar2(20) NOT NULL,
    PWD varchar2(20) NOT NULL,
    NAME varchar2(20) NOT NULL,
    JOB varchar2(30) NULL,
    GRADE varchar2(20) NULL DEFAULT '일반회원',
    POINT number NULL DEFAULT 0,
    CONSTRAINT PK_MEMBER PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
    P_NO number NOT NULL,
    PNAME varchar2(50) NOT NULL,
    PRICE number NOT NULL,
    STOCK number NULL DEFAULT 0,
    KEY number NOT NULL,
    KEY2 date NOT NULL,
    ORDER_NO number NOT NULL,
    ID varchar2(20) NOT NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (P_NO)
);

DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS (
    ORDER_NO number NOT NULL,
    ID varchar2(20) NOT NULL,
    ORDER_COUNT number NOT NULL,
    ADDRESS varchar2(120) NOT NULL,
    ORDER_DATE date NULL DEFAULT SYSDATE,
    P_NO number NOT NULL,
    CONSTRAINT PK_ORDER PRIMARY KEY (ORDER_NO, ID),
    CONSTRAINT FK_MEMBER_TO_ORDER_1 FOREIGN KEY (ID) REFERENCES MEMBER (ID)
);

DROP TABLE IF EXISTS SUPPLY;

CREATE TABLE SUPPLY (
    KEY number NOT NULL,
    KEY2 date NOT NULL,
    FIELD number NULL,
    COMP_NAME varchar2(50) NOT NULL,
    CONSTRAINT PK_SUPPLY PRIMARY KEY (KEY, KEY2)
);

DROP TABLE IF EXISTS COMPANY;

CREATE TABLE COMPANY (
    COMP_NAME varchar2(50) NOT NULL,
    COMP_PHONE varchar2(13) NOT NULL,
    COMP_ADDRESS varchar2(120) NULL,
    COMP_MANAGER varchar2(20) NULL,
    CONSTRAINT PK_COMPANY PRIMARY KEY (COMP_NAME)
);

DROP TABLE IF EXISTS BOARD;

CREATE TABLE BOARD (
    B_NO number NOT NULL,
    B_TITLE varchar2(30) NOT NULL,
    B_CONTENT varchar2(500) NOT NULL,
    B_DATE date NULL DEFAULT SYSDATE,
    ID varchar2(20) NOT NULL,
    CONSTRAINT PK_BOARD PRIMARY KEY (B_NO)
);

DROP TABLE IF EXISTS LIKES;

CREATE TABLE LIKES (
    ID varchar2(20) NOT NULL,
    P_NO number NOT NULL,
    LIKE_DATE date NULL DEFAULT SYSDATE,
    CONSTRAINT PK_LIKE PRIMARY KEY (ID, P_NO),
    CONSTRAINT FK_MEMBER_TO_LIKE_1 FOREIGN KEY (ID) REFERENCES MEMBER (ID),
    CONSTRAINT FK_PRODUCT_TO_LIKE_1 FOREIGN KEY (P_NO) REFERENCES PRODUCT (P_NO)
);
